#! /bin/bash -e
# Link to files in the home folder
BASE=$(cd ${0%/*} && pwd -P)

function link() {
    local source=$1
    local target=$2

    ( [ -L $target ] || [ ! -f $target ] ) || {
        echo "'$target' exists and is not a link, skipping";
        continue;
    }

    mkdir -p $(dirname $target)
    ln --symbolic --force --no-target-directory \
        "${BASE}/$source" $target
}

# Copy dot-files
for SRC in $(find src -type f)
do
    TARGET="$HOME/.${SRC#src/}"
    link $SRC $TARGET
done

# Copy scripts to ~/bin/
for SRC in $(find bin -type f)
do
    TARGET="$HOME/$SRC"
    link $SRC $TARGET
done
