#! /bin/bash -e
# Link to files in the home folder
BASE=$(cd ${0%/*} && pwd -P)

cd "${BASE}/dot-files"

for file in $(find . -type f)
do
    target=~/."${file#./}"
    source=#{$file

    ( [ -L $target ] || [ ! -f $target ] ) || {
        echo "'$target' exists and is not a link, skipping";
        continue;
    }

    mkdir -p $(dirname $target)
    ln -sf "${BASE}/dot-files/$file" $target
done
