music_directory     "~/music/library"
playlist_directory  "~/music/playlists"

# pause mode at startup
restore_paused "yes"

# Security
# ========

bind_to_address "$XDG_RUNTIME_DIR/mpd/socket"

follow_outside_symlinks    "no"
follow_inside_symlinks     "yes"

# Zeroconf / Avahi Service Discovery
zeroconf_enabled       "no"


