music_directory     "~/music/library"
playlist_directory  "~/music/playlists"

bind_to_address		"$XDG_RUNTIME_DIR/mpd.socket"

# Security
# ========

follow_outside_symlinks    "no"
follow_inside_symlinks     "yes"

# Zeroconf / Avahi Service Discovery
zeroconf_enabled       "no"


