#! /bin/bash

function re() {
    source ~/.bashrc
}

function line() {
    local i
    for i in {1..5}; do echo; done;
    [ x"$*" != x"" ] && echo "==== " $*
    echo "================================================="
}

function loop {
    local count=$1; shift
    local no_break=false
    local failures=''
    [ "_$1" = "_--no-break" ] && no_break=true && shift
    for i in $(seq 1 $count); do
        line Run $i
        $* || {
            failures="$failures\nFailed on on run $i\n"
            $no_break || break;
        }
    done

    [ "_$failures" == "_" ] || { echo -e $failures >&2; return 1; }
}

function vw {
    $* 2>&1 | view -
}


function music {
    local playlist=/tmp/playlist
    local music_dir=~/media/music
    find $music_dir -type f -fprint $playlist
    mplayer -shuffle -playlist $playlist
}

function term-title {
    echo -ne "\033]0;" $* "\007"
}
