set nocompatible
" Tab width
set shiftwidth=4
set expandtab
" allow backspacing over everything
set backspace=indent,eol,start
  
" set backup		" keep a backup file
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching

syntax on               " Also switch on highlighting the last used search pattern
set hlsearch            " Switch syntax highlighting on, when the terminal has colors

filetype plugin indent on
set autoindent		" always set autoindenting on

set nobackup
set nowritebackup
set noswapfile
