[[ $- != *i* ]] && return

HISTCONTROL=ignoredups:ignorespace
shopt -s histappend

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

alias    ls='ls   --color=auto'
alias  grep='grep --color=auto'
alias egrep='grep --color=auto'

PS1='\u@\h\$ '

term_title=
function term_title_helper() {
    echo -ne "$term_title" "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"
}

[ "_$TERM" = "_xterm" ] && PROMPT_COMMAND=term_title_helper

EDITOR=kak
type kak >/dev/null 2>/dev/null || EDITOR='vim'
export EDITOR

for file in ~/.bash.d/*; do
    source $file
done

alias dev="sudo systemd-nspawn --directory /var/lib/container/trusty --bind=$HOME -b"

alias lf='ls -CF'
alias ll='ls -l'
alias commit='git commit'
alias sp=line

function re() {
    dot-home-setup "$@"
    source ~/.profile
}

export LC_COLLATE=C
       LANG=en_US.UTF-8

export GOPATH=$HOME/co/go/

# Support for rxvt-unicode-256color missing when ssh-ed, from sbt
[[ $TERM = rxvt-unicode-256color ]] && TERM=xterm
