
all: perlis-epigrams.dat dijkstra.dat programming.dat security-maxims.dat misc.dat 

perlis-epigrams.dat: perlis-epigrams
	strfile perlis-epigrams

dijkstra.dat: dijkstra
	strfile dijkstra

programming.dat: programming
	strfile programming

security-maxims.dat: security-maxims
	strfile security-maxims

misc.dat: misc
	strfile misc
