# Edit and reload kakrc
def -override re %{ source "~/.config/kak/kakrc" }
def -override rc %{ e      "~/.config/kak/kakrc" }

# General options
# ----------------

# Mouse support is annoying, because I don't want the cursor
# to move when I click on the window.
set global ui_options terminal_enable_mouse=false

# Reduce visual pop-up
set-option -add global ui_options terminal_assistant=none # Turn off clippy
set-option global autoinfo ''      # Turn off info boxes
# No autocomplete unless explicitly requested
set-option global autocomplete ''
hook global ModeChange push:.*:insert %{ execute-keys <c-o> }
map global prompt <c-n> '<tab>'    # Use same completion trigger as insert mode

# Hitting the tab key produces 4 space
set global tabstop 4
hook global InsertChar \t %{ exec -draft -itersel h@ }

# Highlighters
# ------------

# Line number
define-command -override    line-numbers %{ add-highlighter global/line-numbers number-lines }
define-command -override no-line-numbers %{ remove-highlighter global/line-numbers }

# Highlight matching braces
hook global WinCreate .* %{ add-highlighter window/show-matching show-matching }

# Highlight the 80th column
define-command -override columns \
   %{   add-highlighter window/columns-80  column  81 default,rgb:dddddd
        add-highlighter window/columns-100 column 101 default,rgb:cccccc
        add-highlighter window/columns-120 column 121 default,rgb:bbbbbb
    }
define-command -override no-columns \
   %{   remove-highlighter window/columns-80
        remove-highlighter window/columns-100
        remove-highlighter window/columns-120
    }
hook global WinCreate .* %{ columns }

# Highlight search; Clear search register on ESC
define-command -override search-highlight    %{ add-highlighter window/search dynregex '%reg{/}' 0:Search }
define-command -override no-search-highlight %{ remove-highlighter window/search }
hook global WinCreate .* %{ search-highlight }
hook global NormalKey <esc> %{ set-register '/' '' }

# Wrapping
define-command -override wrap 	 %{ add-highlighter window/wrap wrap -word }
define-command -override wrap-80 %{ add-highlighter window/wrap wrap -word -width 80 }
define-command -override nowrap %{ remove-highlighter window/wrap }

define-command -override no-spell \
   %{ remove-highlighter window/ranges_spell_regions }

# File Navigation
# ---------------

map global normal <c-n> :buffer-next<ret>
map global normal <c-p> :buffer-previous<ret>


# Select all: space; a
map global user a '*%s<ret>' 	# Search for selection and select all

# Format: space; f
map global user f '|pandoc --from=markdown --to=markdown --columns $kak_opt_textwidth --markdown-headings=setext; echo <ret>'

# Map commands
# ============


# Colors and syntax highlighting
# ------------------------------

# Code
face global value      Default
face global type       Default
face global variable   Default
face global module     Default
face global function   Default
face global string     rgb:559955
face global keyword    Default
face global operator   Default
face global attribute  Default
face global comment    rgb:aaaaaa
face global meta       Default
face global builtin    Default

# Markup
face global title      Default
face global header     Default
face global bold       Default
face global italic     Default
face global mono       Default
face global block      Default
face global link       Default
face global bullet     Default
face global list       Default

# User Interface
face global Search              +bu
face global MatchingChar        rgb:777777+r

face global PrimaryCursor       black+r
face global PrimarySelection    rgb:992222+r
face global SecondaryCursor     rgb:225522+r
face global SecondarySelection  rgb:228822+r


# face global BufferPadding Default
# face global CurrentWord Default
# face global Error Default
# face global Information Default
# face global LineNumberCursor Default
# face global LineNumbers Default
# face global LineNumbersWrapped Default
# face global MatchingChar Default
# face global MenuBackground Default
# face global MenuForeground Default
# face global MenuInfo Default
# face global PrimaryCursor Default
# face global PrimaryCursorEol Default
# face global PrimarySelection Default
# face global Prompt Default
# face global Search Default
# face global SecondaryCursor Default
# face global SecondaryCursorEol Default
# face global SecondarySelection Default
# face global StatusCursor Default
# 1face global StatusLine Default
# face global StatusLineInfo Default
# face global StatusLineMode Default
# face global StatusLineValue Default
# face global Whitespace Default
# face global WrapMarker Default
