def -allow-override re %{ source "~/.config/kak/kakrc" }

# Editor behaviour
# ================

# Mouse support is annoying, because I don't want the cursor
# to move when I click on the window.
set global ui_options ncurses_enable_mouse=false

set global autowrap_column 80
set global tabstop 4
# Expand tabs
hook global InsertChar \t %{ exec -draft -itersel h@ }

#
# Pandoc gripes:
# * should output `shortcut_reference_links`.
# * different levels of bullets should use different chars (e.g. 1st level -, second * ...).
# * LaTeX macros shouldn't be expanded.
#
# TODO: I'm not too happy about using pandoc for formatting,
# because it may be a pain to bring on machines I don't have control over.
# Pandoc markdown to mardown conversion also makes unwanted changes to some entities
# Pandoc should be available as a static binary from the next release
#
# TODO: Use '%opt{textwidth}'; How do I set textwidth?
# TODO: This should only run for markdown files
#
map global user -docstring "Format text" f \
        %{ | pandoc --from=markdown --to=markdown; echo <ret> }
map global normal <F1> "<a-a>p,f<esc><space>k"

# Key bindings
# ============
map global normal S 	:write-all<ret>

# TODO: I would rather have these as `gn`, `gp` to match `ga`, but mapping with
# mode goto doesn't work as I expect (Something to do with selecting?).
map global normal <c-n> :buffer-next<ret>
map global normal <c-p> :buffer-previous<ret>

# Appearance and highlighting
# ===========================

# Highlight matching braces
hook global WinCreate .* %{ add-highlighter show_matching }

# Highlight the 80th column
# TODO: Use '%opt{textwidth}'; How do I set textwidth?
hook global WinCreate .* %{ add-highlighter column '%opt{autowrap_column}' default,rgb:f8f8f8 }

# Colors and syntax
# -----------------

# Code
face value      Default
face type       Default
face variable   Default
face module     Default
face function   Default
face string     rgb:888888
face keyword    Default
face operator   Default
face attribute  Default
face comment    rgb:888888
face meta       Default
face builtin    Default

# Markup
face title      Default
face header     Default
face bold       Default
face italic     Default
face mono       Default
face block      Default
face link       Default
face bullet     Default
face list       Default

face PrimaryCursor default+r
