# This is a very limited tmux configuration for use with kakoune to allow
# split editing. We severely pare down the settings to avoid conflicts
# with nested sessions.

# Prefix: We use an uncommon prefix, C-x, since we expect to be nested in
# tmate during pairing (where we use C-a), and people using tmux as a terminal
# manager.
set -g  prefix C-x    # make prefix key 'x'; avoid common escapes e.g. C-a
unbind-key C-b
bind-key C-x send-prefix

set-option -g set-titles on
set-option -g set-titles-string "tmux: #T"

set -g default-terminal "tmux-256color"

# general ui [1]

set -g  mode-keys        vi     # make ui more vim-like
set -g  status-keys      vi     #
set -s  escape-time      10     # wait time for shortcuts (milliseconds)
set -sg repeat-time      500    # wait time for repeat (milliseconds)
set -g  history-limit    100000 # boost history
set -g  renumber-windows on     # renumber windows when a window is closed
set -g  monitor-activity on     # tell me when something happens

set -g  mouse            off    # disable mouse mode
