#!/bin/bash -e

#require $command $package
function require() {
    command=$1; package=$2
    $command || {
        echo "package '$package' not installed."
        exit 1
    }
}

require "pkg-config x11" "x11 (dev)"
require "pkg-config xinerama" "xinerama (dev)"
require "pkg-config gtk+-2.0" "gtk+2 (dev)"
require "pkg-config webkit-1.0" "webkit (dev)"

BASE=$(cd ${0%/*} && pwd -P)
INSTALL=$HOME/usr
for pgm in dwm dmenu tabbed
do
    cd "$BASE/$pgm"
    make
    rm "$INSTALL/$pgm" || true
    make -s install "PREFIX=$INSTALL"
done
