#!/bin/bash
echo `dbus-launch --sh-syntax`
eval `gnome-keyring-daemon`     # Passwords
eval `cat ~/.fehbg`             # Background

setxkbmap us                    # Layout
xmodmap .Xmodmap                # Disable Caps lock etc.

gnome-settings-daemon &         # Themes etc
gnome-volume-manager &          # auto-mount drives

xfce4-panel &
nm-applet &                     # Network Manager applet

exec openbox
