#! /bin/bash

# setup ccache if it is installed
[ -x /usr/lib/ccache/cc ] && {
    export PATH=/usr/lib/ccache:$PATH
    export CCACHE_COMPRESS=1
}

# Written by curt
mbase() {
    local range_to=false
    [ _"$1" = _-t ] && { range_to=true; shift; }
    local here=${1:-HEAD}
    local there=${2:-origin/master}

    local base=$(git merge-base "$here" "$there")
    if $range_to; then
        echo "$base..$here"
    else
        echo "$base"
    fi
}

function graph() {
    git log --oneline --graph --all --decorate
}

function cpp-color() {
    local command=$*
    $* 2>&1 | egrep  'from here\|error\|undefined reference\|^'
    return ${PIPESTATUS[0]}
}
